// Mock data that stands in for API responses today.
// Once network/api/requests.js and network/api/guarantees.js hit a real
// backend, this file becomes fixtures for tests/storybook rather than
// live app data.

export const initialRequests = [
  {
    id: "req-1",
    contractor: "Al-Fahad Contracting",
    requestedDate: "July 12, 2026",
    applicant: {
      contractorId: "TRV-CTR-11840",
      legalName: "Al-Fahad Contracting LLC",
      cr: "JO-CR-118820",
      tax: "JO-TAX-994512",
      address: "Wadi Saqra, Amman, Jordan",
      contact: "Ahmad Khalil, Operations Director",
      email: "ahmad.khalil@alfahad.jo",
      phone: "+962 79 123 4567",
    },
    project: {
      name: "Al-Noor Tower Construction",
      location: "Amman, Jordan",
      value: "JOD 238,000",
      description: "High-rise residential tower, structural and finishing works",
      duration: "14 months (Sep 2026 – Oct 2027)",
    },
    guarantee: {
      type: "Performance Guarantee",
      amount: "JOD 23,800",
      validity: "Aug 1, 2026 – Oct 31, 2027",
      expiryDate: "2027-10-31",
      conditions: "—",
    },
    beneficiary: {
      company: "Al-Noor Development",
      address: "Shmeisani, Amman, Jordan",
      contact: "Yousef Amer, Development Manager",
      email: "yousef.amer@alnoordev.jo",
      phone: "+962 6 555 8814",
    },
    documents: [
      { name: "Signed Contract / Agreement", status: "Uploaded" },
      { name: "Letter of Award", status: "Uploaded" },
      { name: "Other Supporting Documents", status: "None" },
    ],
    declarations: {
      accuracy: true,
      indemnify: true,
      terms: true,
      signature: "Ahmad Khalil",
    },
  },
  {
    id: "req-2",
    contractor: "Zamzam Builders",
    requestedDate: "July 11, 2026",
    applicant: {
      contractorId: "TRV-CTR-20337",
      legalName: "Zamzam Builders Co.",
      cr: "JO-CR-102244",
      tax: "JO-TAX-771103",
      address: "Al-Rabiah, Amman, Jordan",
      contact: "Salma Odeh, General Manager",
      email: "salma.odeh@zamzambuilders.jo",
      phone: "+962 79 887 2201",
    },
    project: {
      name: "Riverside Complex Phase 2",
      location: "Amman, Jordan",
      value: "JOD 980,000",
      description: "Mixed-use residential and retail complex, civil works",
      duration: "18 months (Sep 2026 – Feb 2028)",
    },
    guarantee: {
      type: "Advance Payment Guarantee",
      amount: "JOD 118,000",
      validity: "Aug 15, 2026 – Feb 28, 2028",
      expiryDate: "2028-02-28",
      conditions: "Reduces proportionally with each certified payment.",
    },
    beneficiary: {
      company: "Riverside Holdings",
      address: "Abdoun, Amman, Jordan",
      contact: "Mazen Tal, Procurement Director",
      email: "mazen.tal@riversideholdings.jo",
      phone: "+962 6 555 3390",
    },
    documents: [
      { name: "Signed Contract / Agreement", status: "Uploaded" },
      { name: "Letter of Award", status: "Uploaded" },
      { name: "Other Supporting Documents", status: "Uploaded" },
    ],
    declarations: {
      accuracy: true,
      indemnify: true,
      terms: true,
      signature: "Salma Odeh",
    },
  },
  {
    id: "req-3",
    contractor: "Horizon Engineering",
    requestedDate: "July 9, 2026",
    applicant: {
      contractorId: "TRV-CTR-33851",
      legalName: "Horizon Engineering LLC",
      cr: "JO-CR-095512",
      tax: "JO-TAX-441987",
      address: "Jubeiha, Amman, Jordan",
      contact: "Nour Saleh, Projects Director",
      email: "nour.saleh@horizoneng.jo",
      phone: "+962 79 440 6612",
    },
    project: {
      name: "Zaytoonah Business Park",
      location: "Amman, Jordan",
      value: "JOD 480,000",
      description: "Commercial fit-out, MEP works",
      duration: "10 months (Aug 2026 – Jun 2027)",
    },
    guarantee: {
      type: "Performance Guarantee",
      amount: "JOD 9,400",
      validity: "Aug 1, 2026 – Jun 30, 2027",
      expiryDate: "2027-06-30",
      conditions: "—",
    },
    beneficiary: {
      company: "Zaytoonah Group",
      address: "Shmeisani, Amman, Jordan",
      contact: "Lina Haddad, Procurement Lead",
      email: "procurement@zaytoonahgroup.jo",
      phone: "+962 6 555 2210",
    },
    documents: [
      { name: "Signed Contract / Agreement", status: "Uploaded" },
      { name: "Letter of Award", status: "Uploaded" },
      { name: "Other Supporting Documents", status: "None" },
    ],
    declarations: {
      accuracy: true,
      indemnify: true,
      terms: true,
      signature: "Nour Saleh",
    },
  },
];

export const initialActive = [
  {
    id: "TRV-GT-65210",
    contractor: "Yarmouk Contracting Est.",
    issuedDate: "July 10, 2026",
    applicant: {
      contractorId: "TRV-CTR-08850",
      legalName: "Yarmouk Contracting Establishment",
      cr: "JO-CR-076651",
      tax: "JO-TAX-330298",
      address: "Sweifieh, Amman, Jordan",
      contact: "Rami Btoush, Managing Partner",
      email: "rami.btoush@yarmoukcontracting.jo",
      phone: "+962 79 502 1187",
    },
    project: {
      name: "Zaytoonah Business Park",
      location: "Amman, Jordan",
      value: "JOD 480,000",
      description: "Commercial fit-out, MEP works",
      duration: "10 months (Aug 2026 – Jun 2027)",
    },
    guarantee: {
      type: "Performance Guarantee",
      amount: "JOD 9,400",
      validity: "Jul 10, 2026 – Jun 30, 2027",
      expiryDate: "2027-06-30",
      conditions: "—",
    },
    beneficiary: {
      company: "Zaytoonah Group",
      address: "Shmeisani, Amman, Jordan",
      contact: "Lina Haddad, Procurement Lead",
      email: "procurement@zaytoonahgroup.jo",
      phone: "+962 6 555 2210",
    },
    documents: [
      { name: "Signed Contract / Agreement", status: "Uploaded" },
      { name: "Letter of Award", status: "Uploaded" },
      { name: "Other Supporting Documents", status: "None" },
    ],
    declarations: {
      accuracy: true,
      indemnify: true,
      terms: true,
      signature: "Rami Btoush",
    },
  },
  {
    id: "TRV-GT-40015",
    contractor: "Cedar Line Interiors",
    issuedDate: "January 14, 2026",
    applicant: {
      contractorId: "TRV-CTR-05512",
      legalName: "Cedar Line Interiors LLC",
      cr: "JO-CR-061238",
      tax: "JO-TAX-118804",
      address: "Khalda, Amman, Jordan",
      contact: "Dana Farah, Owner",
      email: "dana.farah@cedarline.jo",
      phone: "+962 79 330 5567",
    },
    project: {
      name: "Boulevard Retail Fit-out",
      location: "Amman, Jordan",
      value: "JOD 92,000",
      description: "Retail interior fit-out, joinery and finishes",
      duration: "4 months (Dec 2025 – Mar 2026)",
    },
    guarantee: {
      type: "Performance Guarantee",
      amount: "JOD 6,200",
      validity: "Jan 14, 2026 – May 31, 2026",
      expiryDate: "2026-05-31",
      conditions: "—",
    },
    beneficiary: {
      company: "Boulevard Retail Group",
      address: "Abdali, Amman, Jordan",
      contact: "Hazim Qutub, Leasing Manager",
      email: "hazim.qutub@boulevardretail.jo",
      phone: "+962 6 555 7742",
    },
    documents: [
      { name: "Signed Contract / Agreement", status: "Uploaded" },
      { name: "Letter of Award", status: "Uploaded" },
      { name: "Other Supporting Documents", status: "None" },
    ],
    declarations: {
      accuracy: true,
      indemnify: true,
      terms: true,
      signature: "Dana Farah",
    },
  },
];
